version: '3.8'

services:
  frontend:
    image: library-front
    build:
      context: ./frontend/ # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:4000/
    volumes:
      - ./frontend/:/usr/src/app
  backend:                    # The name of the service, can be anything
    image: library-backend   # Declares which image to use
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:                # Declares the ports to publish
      - 3001:3000
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:3456/the_database
    volumes:
      - ./backend/:/usr/src/app
    depends_on:
      - "mongo"
  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js